### ISSUE TITLE
Warnings: deprecated dependencies on building ackee-site

### ISSUE THREAD

**Issue by postblue** [electerious/ackee-site#1]
Configuration:
* npm 3.5.2
* node v5.3.0

Routine:
```
git clone https://github.com/electerious/Ackee.git -b v2
cd Ackee
git submodule init && git submodule update
npm run-script build
npm start
```
Warnings:
```
npm WARN deprecated lodash@1.0.2: lodash@<2.0.0 is no longer maintained. Upgrade to lodash@^3.0.0
npm WARN deprecated npmconf@2.1.2: this package has been reintegrated into npm and is now out of date with respect to npm
```

**Comment by electerious** [comment]
All dependencies match the latest package versions. Those warning are from dependencies of dependencies, which I can't modify.

**Comment by postblue** [comment]
OK, thank you for the explanation! :) I'm continuing to try the baby, it's quite fun to understand how it works without any README. :D
